apiVersion: v1
kind: Secret
metadata:
  name: {{ include "madrag.fullname" . }}-env
  labels:
    {{- include "madrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "madrag.envContent" . | nindent 4 }}
